#!/usr/bin/env bash

PUID=${PUID:-0}
PGID=${PGID:-0}

# GUID between 1-99 are typically reserved for system use, so we warn the user
if [[ "$PUID" -lt 100 && "$PUID" -ne 0 ]]; then
    echo "The provided PGID is below 100. This is typically reserved for system use and may cause unexpected behavior."
fi

groupmod -o -g "$PGID" bitwarden
usermod -o -u "$PUID" bitwarden

echo " _                                             _   ";
echo "| |____      __      _____  ___ __   ___  _ __| |_ ";
echo "| '_ \ \ /\ / /____ / _ \ \/ / '_ \ / _ \| '__| __|";
echo "| |_) \ V  V /_____|  __/>  <| |_) | (_) | |  | |_ ";
echo "|_.__/ \_/\_/       \___/_/\_\ .__/ \___/|_|   \__|";
echo "                             |_|                   ";
echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u bitwarden)
User gid:    $(id -g bitwarden)
-------------------------------------
"
chown -R  bitwarden:bitwarden /app
chown -R  bitwarden:bitwarden /var/data
chown -R  bitwarden:bitwarden /var/attachment
